apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
  namespace: cert-manager
spec:
  acme:
    email: <email-address>
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:  
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: <IAM ACCESS KEY>
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: password.txt
      selector:
        dnsZones:
        - 'viktoriouslab.nl'
