apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: cluster-01
  namespace: tap
spec:
  topology:
    controlPlane:
      count: 3
      class: best-effort-medium
      storageClass: tanzu-storage-policy
    workers:
      count: 3
      class: best-effort-4p-8gb
      storageClass: tanzu-storage-policy
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 100Gi
  distribution:
    version: 1.23.8+vmware.3-tkg.1
  settings:
    network:
      cni:
        name: antrea #But could be left blank if using the default
      services:
        cidrBlocks: ["10.99.0.0/16"]
      pods:
        cidrBlocks: ["10.98.0.0/16"]
      trust:
        additionalTrustedCAs:
          - name: InternalCA
            data: 
          - name: Harbor
            data: 
    storage:
      defaultClass: tanzu-storage-policy