apiVersion: v1
kind: Secret
metadata:
  name: tap-registry
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
secrets:
  - name: registry-credentials
  - name: tap-registry
  #
  # Only add the next line if you're using the supply_chain: testing or testing_scanning setting in tap-values.yaml
  # By default Tekton will pull test images from dockerhub. If you're using another registry for this, access to Dockerhub is not required.
  # The Dockerhub account is required for solves rate-limiting issues: https://docs.docker.com/docker-hub/download-rate-limit/
  #
  - name: dockerhub-credentials
imagePullSecrets:
  - name: registry-credentials
  - name: tap-registry
  #
  # Only add the next line if you're using the supply_chain: testing or testing_scanning setting in tap-values.yaml
  # By default Tekton will pull test images from dockerhub. If you're using another registry for this, access to Dockerhub is not required. 
  # The Dockerhub account is required for solves rate-limiting issues: https://docs.docker.com/docker-hub/download-rate-limit/
  #
  - name: dockerhub-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-deliverable
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-permit-workload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
  - kind: ServiceAccount
    name: default
